#ifndef FR_LUA_NAMES_H
#define FR_LUA_NAMES_H

#define FR_CLIENT_LUA_MAIN_TABLE    "fr"
#define FR_CLIENT_LUA_HIDE_TABLE    "frhide"

#define FR_CLIENT_LUA_CLIENT_TABLE  FR_CLIENT_LUA_MAIN_TABLE ".client"

#define FR_CLIENT_GEN_INFO_PATH     FR_CLIENT_LUA_HIDE_TABLE ".gen_info"
#define FR_CLIENT_WD_PATH           FR_CLIENT_LUA_HIDE_TABLE ".wd"


#endif // FR_LUA_NAMES_H
