#ifndef FR_LUA_NAMES_H
#define FR_LUA_NAMES_H

#define FR_CLIENT_LUA_MAIN_TABLE "fr"
#define FR_CLIENT_LUA_HIDE_TABLE "frhide"

#define FR_CLIENT_LUA_CLIENT_TABLE FR_CLIENT_LUA_MAIN_TABLE ".client"

#define FR_CLIENT_GEN_INFO_PATH FR_CLIENT_LUA_HIDE_TABLE ".gen_info"


#endif // FR_LUA_NAMES_H
